#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
xsetroot -solid "#151515" &
~/.config/polybar/launch.sh &
#xfce4-session &
pcmanfm -d &
#picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2

bspc config split_ratio          	  0.50
bspc config gapless_monocle      	  true
bspc config focus_follows_pointer         true

bspc config normal_border_color		      "#6A6A6A"
bspc config active_border_color	              "#6A6A6A"
bspc config focused_border_color	      "#8f8f8f"
bspc config presel_feedback_color	      "#8f8f8f"
bspc config urgent_border_color 	      "#6A6A6A"

wmname LG3D

bspc rule -a Emacs state=tiled
