#! /bin/sh

sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
setxkbmap gb &
light -S 20 &
./.config/polybar/launch.sh &
lxsession &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3

bspc config split_ratio          	  0.50
bspc config gapless_monocle      	  true
bspc config focus_follows_pointer         true

bspc config normal_border_color		      "#7c7c7c"
bspc config active_border_color	              "#868686"
bspc config focused_border_color	      "#b9b9b9"
bspc config presel_feedback_color	      "#b9b9b9"
bspc config urgent_border_color 	      "#ffffff"

wmname LG3D

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled



mygames=$(ls ~/.steam/steam/steamapps | grep appmanifest | sed 's/[^0-9]*//g')
# this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^9 state=fullscreen follow=on
done
