#! /bin/sh

sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
./.config/polybar/launch.sh &
lxsession &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3

bspc config split_ratio          	  0.50
bspc config gapless_monocle      	  true
bspc config focus_follows_pointer         true

bspc config normal_border_color		      "#fefefe"
bspc config active_border_color	              "#ffffff"
bspc config focused_border_color	      "#b1b1b1"
bspc config presel_feedback_color	      "#525252"
bspc config urgent_border_color 	      "#ffffff"

wmname LG3D

bspc rule -a Emacs state=tiled
