swipe:
  3: 
    left:
      command: bspc desktop -f prev
    right: 
      command: bspc desktop -f next
    up: 
      command: rofi -show drun
pinch:
  in:
    window:
      fullscreen: toggle
  out:
    window:
      fullscreen: toggle
tap:
  2:
    sendkey:

threshold:
  swipe: 0.3
  pinch: 0.1

interval:
  swipe: 1.0
  pinch: 3.0
